{"timestamp":"2025-09-23T00:27:29.112945","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-23T00:27:29.120073","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/p_spotipy.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-23T00:27:31.117954Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.124221Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.125192Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.125507Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.125933Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.126221Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.126468Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.126690Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.126925Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.127151Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.127414Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.127623Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.127866Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.128107Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.128317Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.128508Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.128828Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.129369Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.129716Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.130179Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.130712Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.131009Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.131517Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.131859Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.132133Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.132466Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.132907Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.133196Z","level":"info","event":"sql here","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.133472Z","level":"info","event":"Connection failed: (pymysql.err.OperationalError) (2003, \"Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)\")","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.133713Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-23T00:27:31.151872","level":"info","event":"Done. Returned value was: None","logger":"airflow.task.operators.airflow.providers.standard.operators.python.PythonOperator"}
